### ISSUE TITLE
Exact version of Xen to be used

### ISSUE THREAD

**Issue by d34d10cc** [tklengyel/xen-uefi#1]
Not an issue, per se, but I cannot, for the life of me, figure out what exact version (commit?) of Xen should be used with these instructions. When applying the third Xen patch, no matter which 4.10.0 release I use, I get:
```
patching file xen/include/xen/efi.h
Hunk #1 FAILED at 44.
1 out of 1 hunk FAILED -- saving rejects to file xen/include/xen/efi.h.rej
```
And of course, it doesn't compile like that, throwing an error about the `efi_secureboot_enabled` function. I'd appreciate help with this and the information could possibly be included in the README along with a link? Thanks in advance.

**Comment by Quantomicus** [comment]
On closer inspection, the Xen version doesn't seem to matter, at least in respects to this patch fail. It seems to be related to [this kernel patch](https://patchwork.kernel.org/patch/9103601/) where the `efi_secureboot_enabled` function is removed.

**Comment by d34d10cc** [comment]
Although, upon closer inspection, the Xen repository never included a declaration of the function in `efi.h`. Is one supposed to use some modified version of Xen, or does the patch lack some modifications? I am asking because simply adding the declaration like it is in the patch manually does not help at all. It changes the error message displayed, but other than that, nothing.

**Comment by tklengyel** [comment]
The patches were on top of xen-unstable but I see with that latest head it no longer applies. You can use https://github.com/tklengyel/xen/tree/srtm-drtm and I'll add a submodule for it to avoid having to manually patch.

**Comment by d34d10cc** [comment]
Thank you very much for these wonderful workarounds!
