### ISSUE TITLE
"Boot succeeded - SHIM"

### ISSUE THREAD

**Issue by d34d10cc** [tklengyel/xen-uefi#2]
This is certainly not the place for it, but after performing all the steps, and having to fiddle with my quirky BIOS to make it allow shim to even boot, when booting into shim from the boot manager, I only get the message in the title, after which it just reverts to the boot manager. I can boot into GRUB after the fact, but I cannot figure out what happens after the message I get. Are there any places shim might leave logs?

EDIT: Upon closer inspection with a camera, the output is the following:
```
Boot Succeeded - SHIM
Xen 4.10.1 (c/s ) EFI loader
Using configuration file 'shim.cfg'
vmlinuz-4.17.2-20.fc28.x86_64: <memory address> - <memory address>
```

**Comment by tklengyel** [comment]
Nope, the shim only prints to the screen. You might want to get a serial connction to your machine to see how far it gets in the boot process.
